/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete.grafica;


import java.util.ArrayList;
import java.util.List;
import javax.accessibility.AccessibleContext;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTable;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import paquete.clases.Cliente;
import paquete.clases.*;
import paquete.clases.Vuelo;
import paquete.gestion.GestionPersona;
import paquete.gestion.GestionReserva;
import paquete.gestion.GestionVuelo;

/**
 *
 * @author mateh
 */
public class VentanaReserva extends javax.swing.JFrame 
{
    private GestionPersona usuario1;
    private GestionReserva refGReserva;
    private List<String> listaDepartamentos;
    private DefaultTableModel modelo;
    private DefaultTableModel modelo2;
    private Reserva reserva;
    

    /**
     * Creates new form VentanaReserva
     */
    
    public VentanaReserva() {
        initComponents();
        inicializar();
        setLocationRelativeTo(this);
        // para el spinner PASAJEROS
        SpinnerNumberModel nm = new SpinnerNumberModel();
        nm.setMinimum(0);
        nm.setMaximum(10);
        this.jSpinner1.setModel(nm);        
       
        // para la tabla de ida
        modelo = new DefaultTableModel();
        modelo.addColumn("FECHA");
        modelo.addColumn("PRECIO");
        modelo.addColumn("ORIGEN");
        modelo.addColumn("DESTINO");
        modelo.addColumn("HORA");
        modelo.addColumn("COD. VUELO");
        modelo.addColumn("TICKET");
        modelo.addColumn("MATRICULA");
        modelo.addColumn("CLASE");

        
        // para la tabla de vuelta
        modelo2 = new DefaultTableModel();
        modelo2.addColumn("FECHA");
        modelo2.addColumn("PRECIO");
        modelo2.addColumn("ORIGEN");
        modelo2.addColumn("DESTINO");
        modelo2.addColumn("HORA");
        modelo2.addColumn("COD. VUELO");
        modelo2.addColumn("TICKET");
        modelo2.addColumn("MATRICULA");
        modelo2.addColumn("CLASE");
        
        // Llenar tablas
        this.jTable1.setModel(modelo);
        this.jTable2.setModel(modelo2);
        

    }
    // GESTION PERSONA

    public GestionPersona getUsuario1() {
        return usuario1;
    }

    public void setUsuario1(GestionPersona usuario1) {
        this.usuario1 = usuario1;
    }
    
    
    // GESTION RESERVA

    public GestionReserva getRefGReserva() {
        return refGReserva;
    }

    public void setRefGReserva(GestionReserva refGReserva) {
        this.refGReserva = refGReserva;
    }
    
    public Reserva getReserva() {
        return reserva;
    }

    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel5.setText("FECHA DE RETORNO");

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel10.setText("INGRESE COD. TICKET VUELTA");

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setText("RESERVA");

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel6.setText("PASAJEROS");

        jButton5.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jButton5.setText("RESERVAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel2.setText("ORIGEN");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jButton6.setText("MIS RESERVAS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel8.setText("IDA");

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel3.setText("DESTINO");

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel4.setText("FECHA DE IDA");

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel9.setText("VUELTA");

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel7.setText("INGRESE COD. TICKET IDA");

        jButton2.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jButton2.setText("CERRAR SESION");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(85, 85, 85)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel6)))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel7)
                                .addGap(33, 33, 33)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jButton2)
                                .addGap(194, 194, 194)
                                .addComponent(jLabel1)
                                .addGap(86, 86, 86)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButton1)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton6)
                    .addComponent(jButton2)
                    .addComponent(jLabel11))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        VentanaReservasActivas vra = new VentanaReservasActivas();
        vra.setRefGR(refGReserva);
        vra.setUsuario2(usuario1);
        vra.mostrarTablaInicial();
        vra.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal vp = new VentanaPrincipal();
        vp.setRefRE(refGReserva);
        vp.setRefGP(usuario1);
        vp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        // BOTON RESERVAR
        // Al presionar el boton reservar almacena todo la informacion, recalcula el precio*asientos vuelo, toma el codigo del vuelo
        String codTicketIda = this.jTextField3.getText();
        String codTicketVuelta = this.jTextField4.getText();
        String codVueloIda = obtenerVuelo(jTable1,codTicketIda);
        String codVueloVuelta = obtenerVuelo(jTable2,codTicketVuelta);
        //
        float precioIda = obtenerMonto(jTable1,codTicketIda);
        float precioVuelta = obtenerMonto(jTable2,codTicketVuelta);
        
         //INICIALIZO LA RESERVA
        reserva = new Reserva(usuario1.getUsuarioSesion().getCodigoCliente(),(Integer)this.jSpinner1.getValue());
        reserva.setCodigoTicketIda(codTicketIda);
        reserva.setCodigoTicketVuelta(codTicketVuelta);
        reserva.setCodigovueloIda(codVueloIda);
        reserva.setCodigovueloRetorno(codVueloVuelta);
        reserva.setCodigoCliente(usuario1.getUsuarioSesion().getCodigoCliente());
        reserva.setNumeroPasajeros((Integer)this.jSpinner1.getValue());
        float monto = precioIda*reserva.getNumeroPasajeros() + precioVuelta*reserva.getNumeroPasajeros();
        reserva.setMontoTotal(monto);
        this.refGReserva.ValidarDatosReserva(reserva);
        this.refGReserva.Ingresar(reserva);
        
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private String obtenerVuelo(JTable tabla, String ticketIda) {
        String codigo = "";
        
        //filas de la tabla
        for (int i = 0; i < tabla.getRowCount(); i++) 
        {  // Loop through the rows
            DefaultTableModel mod = (DefaultTableModel)tabla.getModel();
            String ticket =  mod.getValueAt(i, 6).toString(); 
            if (ticket.equals(ticketIda)){
                // para obtener el codigo del vuelo de la tabla para posteriormente ser reflejada en la siguiente pagina
                codigo = mod.getValueAt(i, 5).toString(); 
                break;
            }
        }
        return codigo;
    }
    
    private float obtenerMonto(JTable tabla, String ticketIda) {
        float codigo = 0.0f;
        
        //Obtiene el monto de la tabla asignada

        for (int i = 0; i < tabla.getRowCount(); i++) 
        {  // Loop through the rows
            DefaultTableModel mod = (DefaultTableModel)tabla.getModel();
            // para obtener el precio que muestra la tabla para posteriormente ser reflejada en la siguiente pagina
            String ticket =  mod.getValueAt(i, 6).toString(); 
            if (ticket.equals(ticketIda)){
                codigo = Float.parseFloat(mod.getValueAt(i, 1).toString()); 
                break;
            }
        }
        return codigo;
    }
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        //evento de seleccionar
        //guardar en una variable lo seleccionado
        String sele = (String)this.jComboBox1.getSelectedItem();
        List<String> lista2 = new ArrayList<String>();
        for(int i=0;i<listaDepartamentos.size();i++)
        {
            if(listaDepartamentos.get(i)!=sele)
            {
                lista2.add(listaDepartamentos.get(i));
            }
        }
        
        jComboBox2.setModel(new DefaultComboBoxModel<String>(lista2.toArray(new String[0])));
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String origen = this.jComboBox1.getSelectedItem().toString();
        String destino = this.jComboBox2.getSelectedItem().toString();
        String fechaida = this.jTextField1.getText();
        String fechavuelta = this.jTextField2.getText();
        

        //Interaccion con la tabla

        Vuelo[] vOrigen = refGReserva.getgVuelo().BuscarVuelos(origen, destino, fechaida);
        if (vOrigen.length >0)
        {
            CargarDatosTablaIda(vOrigen);
            Vuelo[] vDestino = refGReserva.getgVuelo().BuscarVuelos(destino, origen, fechavuelta);
            CargarDatosTablaVuelta(vDestino);
            
        }

 
    }//GEN-LAST:event_jButton1ActionPerformed

    public void CargarDatosTablaIda(Vuelo[] lista)
    {
        int filas = this.jTable1.getRowCount();
        for (int i = 0; i < filas; i++) 
        {
            modelo.removeRow(0);
        }

        String[] datos = new String[9];
        for (int i = 0; i < lista.length; i++) 
        {
            if (lista[i] != null) 
            {
                datos[0] = lista[i].getFechaVuelo();
                datos[1] = String.valueOf(lista[i].getMontoFinal());
                datos[2] = lista[i].getOrigen();
                datos[3] = lista[i].getDestino();
                datos[4] = lista[i].getHora();
                datos[5] = lista[i].getCodigoVuelo();
                datos[6] = lista[i].getTicket();
                datos[7] = lista[i].getMatricula();
                
                if (lista[i] instanceof VEconomico) 
                {
                    datos[8] = "ECONOMICO";
                } 
                else if (lista[i] instanceof VPremium) 
                {
                    datos[8] = "PREMIUM";
                } 
                else if (lista[i] instanceof VBusiness) 
                {
                    datos[8] = "BUSINESS";
                }
                
                

                modelo.addRow(datos);
            }
        }
    }
    public void CargarDatosTablaVuelta(Vuelo[] lista)
    {
        int filas = this.jTable2.getRowCount();
        for (int i = 0; i < filas; i++) 
        {
            modelo2.removeRow(0);
        }

        String[] datos = new String[9];
        for (int i = 0; i < lista.length; i++) 
        {
            if (lista[i] != null) 
            {

                datos[0] = lista[i].getFechaVuelo();
                datos[1] = String.valueOf(lista[i].getMontoFinal());
                datos[2] = lista[i].getOrigen();
                datos[3] = lista[i].getDestino();
                datos[4] = lista[i].getHora();
                datos[5] = lista[i].getCodigoVuelo();
                datos[6] = lista[i].getTicket();
                datos[7] = lista[i].getMatricula();
                if (lista[i] instanceof VEconomico) 
                {
                    datos[8] = "ECONOMICO";
                } 
                else if (lista[i] instanceof VPremium) 
                {
                    datos[8] = "PREMIUM";
                } 
                else if (lista[i] instanceof VBusiness)
                {
                    datos[8] = "BUSINESS";
                }

                modelo2.addRow(datos);
            }
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

    private void inicializar() {
        listaDepartamentos = new ArrayList<String>();
        // objetos genéricos
        listaDepartamentos.add("LIMA");
        listaDepartamentos.add("CUZCO");
        listaDepartamentos.add("AREQUIPA");
        listaDepartamentos.add("CHICLAYO");
        listaDepartamentos.add("TARAPOTO");
        
        jComboBox1.setModel(new DefaultComboBoxModel<String>(listaDepartamentos.toArray(new String[0])));
        jComboBox2.setModel(new DefaultComboBoxModel<String>(listaDepartamentos.toArray(new String[0])));
        
        
    }

    
}
