/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete.grafica;

import javax.swing.table.DefaultTableModel;
import paquete.clases.Reserva;
import paquete.clases.VBusiness;
import paquete.clases.VEconomico;
import paquete.clases.VPremium;
import paquete.clases.Vuelo;
import paquete.gestion.GestionPersona;
import paquete.gestion.GestionReserva;
import paquete.gestion.GestionVuelo;

/**
 *
 * @author mateh
 */
public class VentanaReservasActivas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaReservasActivas
     */
    private GestionPersona usuario2;
    private GestionReserva refGR;
    private DefaultTableModel modelo;
    private Reserva reserva2;
    
    
    public VentanaReservasActivas() {
        initComponents();
        setLocationRelativeTo(this);
        
        //tabla
        modelo = new DefaultTableModel();
        
        modelo.addColumn("FECHA");
        modelo.addColumn("PRECIO");
        modelo.addColumn("ORIGEN");
        modelo.addColumn("DESTINO");
        modelo.addColumn("HORA");
        modelo.addColumn("COD. VUELO");
        modelo.addColumn("TICKET");
        modelo.addColumn("MATRICULA");
        modelo.addColumn("CLASE");
        modelo.addColumn("ASIENTOS");
        modelo.addColumn("IDA/VUELTA");
        modelo.addColumn("NUM. RESERVA");
        this.jTable1.setModel(modelo);  
       /* Reserva[] lista = refGR.BuscarReservaPorID(usuario2.getUsuarioSesion().getCodigoCliente());
        CargarDatosTabla(lista);*/
        
        
    }

    public GestionReserva getRefGR() {
        return refGR;
    }

    public void setRefGR(GestionReserva refGR) {
        this.refGR = refGR;
    }

    public GestionPersona getUsuario2() {
        return usuario2;
    }

    public void setUsuario2(GestionPersona usuario2) {
        this.usuario2 = usuario2;
    }

    public Reserva getReserva2() {
        return reserva2;
    }

    public void setReserva2(Reserva reserva2) {
        this.reserva2 = reserva2;
    }
    
    public void mostrarTablaInicial()
    {
        Reserva[] lista = refGR.BuscarReservaPorID(usuario2.getUsuarioSesion().getCodigoCliente());
        CargarDatosTabla(lista);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jButton2.setText("INGRESAR NUEVA RESERVA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jButton4.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jButton4.setText("CERRAR SESION");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RESERVAS ACTIVAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1140, 206));

        jButton5.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jButton5.setText("CANCELAR RESERVA");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, -1, -1));

        jTextField1.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 360, 117, 23));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/imagenes/Logo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -20, 170, 190));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/imagenes/fondo.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1158, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal vp = new VentanaPrincipal();
        vp.setRefRE(refGR);
        vp.setRefGP(usuario2);
        vp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        VentanaReserva vreserva = new VentanaReserva();
        vreserva.setVisible(true);
        vreserva.setRefGReserva(refGR);
        vreserva.setUsuario1(usuario2);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        int codigoReserva = Integer.parseInt(this.jTextField1.getText());
        refGR.Eliminar(codigoReserva);
        Reserva[] lista = refGR.BuscarReservaPorID(usuario2.getUsuarioSesion().getCodigoCliente());
        CargarDatosTabla(lista);
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    public void CargarDatosTabla(Reserva[] lista)
    {
        
        int filas = this.jTable1.getRowCount();
        for (int i = 0; i < filas; i++) 
        {
            modelo.removeRow(0);
        }
                
        for (int i = 0; i < lista.length; i++) 
        {
            if (lista[i] != null) 
            {
                //obenemos los datos del vuelo de ida
                Vuelo vIda = refGR.getgVuelo().BuscarVueloActivo(lista[i].getCodigovueloIda(), lista[i].getCodigoTicketIda());
                Vuelo vRegreso = refGR.getgVuelo().BuscarVueloActivo(lista[i].getCodigovueloRetorno(), lista[i].getCodigoTicketVuelta());
                String[] datos = obtenerFilaTabla(vIda, lista[i], "IDA");
                modelo.addRow(datos);
                datos = obtenerFilaTabla(vRegreso, lista[i], "VUELTA");
                modelo.addRow(datos);
            }
        }

    }
    
            
    public String[] obtenerFilaTabla(Vuelo vIda, Reserva res, String tipo) {
        String[] datos = new String[12];
        datos[0] = vIda.getFechaVuelo();
        datos[1] = String.valueOf(vIda.getMontoFinal()*res.getNumeroPasajeros());
        datos[2] = vIda.getOrigen();
        datos[3] = vIda.getDestino();
        datos[4] = vIda.getHora();
        datos[5] = vIda.getCodigoVuelo();
        datos[6] = vIda.getTicket();
        datos[7] = vIda.getMatricula();

        if (vIda instanceof VEconomico) {
            datos[8] = "ECONOMICO";
        } else if (vIda instanceof VPremium) {
            datos[8] = "PREMIUM";
        } else if (vIda instanceof VBusiness) {
            datos[8] = "BUSINESS";
        }
        datos[9] = String.valueOf(res.getNumeroPasajeros());
        datos[10] = tipo;
        datos[11] = String.valueOf(res.getCodigoReserva());
        
        //Reserva se trae codigo del cliente
        return datos;
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaReservasActivas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaReservasActivas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaReservasActivas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaReservasActivas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaReservasActivas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
